# Gopkg.toml
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.

ignored = [ "github.com/oscartbeaumont/go-utils*" ] # TEMP: During Development

[[constraint]]
  name = "github.com/99designs/gqlgen"
  version = "0.7.1"

[[constraint]]
  name = "github.com/kataras/muxie"
  version = "1.0.6"

[[constraint]]
  name = "github.com/rs/zerolog"
  version = "1.11.0"

[[constraint]]
  branch = "master"
  name = "github.com/shurcooL/httpgzip"

[[constraint]]
  branch = "master"
  name = "github.com/shurcooL/vfsgen"

[[constraint]]
  name = "github.com/vektah/gqlparser"
  version = "1.0.0"

[[constraint]]
  name = "github.com/micromdm/scep"
  version = "1.0.0"

[prune]
  go-tests = true
  unused-packages = true
