[[constraint]]
  name = "github.com/RobotsAndPencils/buford"
  version = "0.12.0"

[[constraint]]
  name = "github.com/go-pg/pg"
  version = "6.14.3"

[[constraint]]
  name = "github.com/gorilla/handlers"
  version = "1.3.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.2"

[[constraint]]
  branch = "master"
  name = "github.com/groob/plist"

[[constraint]]
  branch = "master"
  name = "github.com/oscartbeaumont/gonfig"

[[constraint]]
  name = "github.com/rifflock/lfshook"
  version = "2.3.0"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.6"

[prune]
  go-tests = true
  unused-packages = true
