[[constraint]]
  name = "github.com/go-chi/chi"
  version = "3.3.3"

[[constraint]]
  name = "github.com/go-kit/kit"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/groob/plist"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"

[prune]
  go-tests = true
  unused-packages = true
